/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface ApiTokenCalls {
  calls: number;
  minute: Int8;
  org_id: string;
  token_id: string;
}

export interface ApiTokens {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  name: string;
  org_id: string;
  prefix: string;
  project_id: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
}

export interface Artifacts {
  content_type: string;
  created_at: Generated<Timestamp>;
  discarded_at: Timestamp | null;
  finding_key: string | null;
  id: Generated<string>;
  job_id: string;
  kind: string;
  org_id: string;
  run_id: string;
  size_bytes: number;
  storage_key: string;
  stored_at: Timestamp | null;
}

export interface Credentials {
  base_url: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  hint: string;
  id: Generated<string>;
  kind: string;
  org_id: string;
  secret: string;
}

export interface FindingDismissals {
  dismissed_at: Generated<Timestamp>;
  dismissed_by: string;
  finding_key: string;
  matched_finding_key: string | null;
  matched_run_id: string | null;
  org_id: string;
  reason: string;
  run_id: string;
}

export interface Findings {
  created_at: Generated<Timestamp>;
  filed_as: string | null;
  goal: string;
  id: Generated<string>;
  job_id: string;
  key: string;
  kind: string;
  observed: string;
  org_id: string;
  persona_key: string;
  quote: string | null;
  replay: Json | null;
  reproduction: Json;
  run_id: string;
  same_as: string | null;
  severity: string;
  step_people: Json | null;
  title: string;
  updated_at: Generated<Timestamp>;
  url: string | null;
  verdict: string | null;
}

export interface FirstRunsOnUs {
  model_called_at: Timestamp | null;
  org_id: string;
  run_id: string;
  used_at: Generated<Timestamp>;
}

export interface GoalOutcomes {
  goal: string;
  note: Generated<string>;
  org_id: string;
  persona_key: string;
  run_id: string;
  status: string;
}

export interface Goals {
  id: Generated<string>;
  instruction: string;
  key: string;
  org_id: string;
  persona_key: string;
  plan_id: string;
  position: number;
  project_id: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Jobs {
  account_ref: string | null;
  counted_cost: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  error: string | null;
  finding_key: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  lease_until: Timestamp | null;
  org_id: string;
  persona_key: string | null;
  position: number;
  requested_by: string | null;
  run_id: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  stopped_by: string | null;
  together: Generated<boolean>;
  token_hash: string | null;
  usage: Json | null;
}

export interface LlmUsage {
  cost_usd: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  input_tokens: number;
  job_id: string;
  model: string;
  org_id: string;
  output_tokens: number;
  paid_by: Generated<string>;
  run_id: string;
}

export interface McpCodeClaims {
  code_hash: string;
  expires_at: Timestamp;
}

export interface McpCodeProjects {
  code_hash: string;
  expires_at: Timestamp;
  org_id: string;
  project_id: string;
}

export interface McpConsentContexts {
  expires_at: Timestamp;
  flow_hash: string;
  org_id: string;
  project_id: string | null;
  user_id: string;
}

export interface McpGrants {
  client_id: string;
  code_hash: string;
  created_at: Generated<Timestamp>;
  id: string;
  last_used_at: Timestamp | null;
  org_id: string;
  project_id: string | null;
  resource: string;
  revoked_at: Timestamp | null;
  scopes: string[];
  user_id: string;
}

export interface McpRateLimits {
  calls: number;
  key: string;
  minute: Int8;
}

export interface Member {
  createdAt: Timestamp;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface ModelCatalog {
  completion_usd_per_mtok: Numeric;
  enabled: Generated<boolean>;
  id: string;
  label: string;
  note: string | null;
  position: number;
  prices_refreshed_at: Timestamp | null;
  prompt_usd_per_mtok: Numeric;
  recommended: Generated<boolean>;
}

export interface OauthAccessToken {
  authorizationCodeId: string | null;
  clientId: string;
  confirmation: Json | null;
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  referenceId: string | null;
  refreshId: string | null;
  requestedUserInfoClaims: Json | null;
  resources: Json | null;
  revoked: Timestamp | null;
  scopes: Json;
  sessionId: string | null;
  token: string;
  userId: string | null;
}

export interface OauthClient {
  applicationType: string | null;
  backchannelLogoutSessionRequired: boolean | null;
  backchannelLogoutUri: string | null;
  clientCredentialsScopes: Json | null;
  clientDiscoveryId: string | null;
  clientId: string;
  clientSecret: string | null;
  contacts: Json | null;
  createdAt: Timestamp | null;
  disabled: boolean | null;
  dpopBoundAccessTokens: boolean | null;
  enableEndSession: boolean | null;
  grantTypes: Json | null;
  icon: string | null;
  id: string;
  jwks: string | null;
  jwksUri: string | null;
  metadata: Json | null;
  name: string | null;
  policy: string | null;
  postLogoutRedirectUris: Json | null;
  redirectUris: Json;
  referenceId: string | null;
  requirePKCE: boolean | null;
  responseTypes: Json | null;
  scopes: Json | null;
  skipConsent: boolean | null;
  softwareId: string | null;
  softwareStatement: string | null;
  softwareVersion: string | null;
  subjectType: string | null;
  tokenEndpointAuthMethod: string | null;
  tos: string | null;
  updatedAt: Timestamp | null;
  uri: string | null;
  userId: string | null;
}

export interface OauthClientAssertion {
  expiresAt: Timestamp;
  id: string;
}

export interface OauthClientResource {
  clientId: string;
  createdAt: Timestamp | null;
  id: string;
  metadata: Json | null;
  resourceId: string;
}

export interface OauthConsent {
  clientId: string;
  createdAt: Timestamp;
  id: string;
  referenceId: string | null;
  requestedUserInfoClaims: Json | null;
  resources: Json | null;
  scopes: Json;
  updatedAt: Timestamp;
  userId: string | null;
}

export interface OauthRefreshToken {
  authorizationCodeId: string | null;
  authTime: Timestamp | null;
  clientId: string;
  confirmation: Json | null;
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  referenceId: string | null;
  requestedUserInfoClaims: Json | null;
  resources: Json | null;
  revoked: Timestamp | null;
  rotatedAt: Timestamp | null;
  rotationReplayExpiresAt: Timestamp | null;
  rotationReplayResponse: string | null;
  scopes: Json;
  sessionId: string | null;
  token: string;
  userId: string;
}

export interface OauthResource {
  accessTokenTtl: number | null;
  allowedScopes: Json | null;
  createdAt: Timestamp | null;
  customClaims: Json | null;
  disabled: boolean | null;
  dpopBoundAccessTokensRequired: boolean | null;
  id: string;
  identifier: string;
  metadata: Json | null;
  name: string;
  policyVersion: number | null;
  refreshTokenTtl: number | null;
  signingAlgorithm: string | null;
  signingKeyId: string | null;
  updatedAt: Timestamp | null;
}

export interface Organization {
  createdAt: Timestamp;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Personas {
  account_ref: string | null;
  brief: string;
  id: Generated<string>;
  key: string;
  name: string;
  org_id: string;
  plan_id: string;
  position: number;
  project_id: string;
  signs_in: Generated<boolean>;
}

export interface Plans {
  account_flow: string | null;
  account_reason: string | null;
  brief: string | null;
  created_at: Generated<Timestamp>;
  created_by_run_id: string | null;
  features: Generated<string[]>;
  id: Generated<string>;
  inputs_hash: string | null;
  kind: Generated<string>;
  last_used_at: Timestamp | null;
  name: string;
  org_id: string;
  position: Generated<number>;
  pr_number: number | null;
  project_id: string;
  repo: string | null;
  source_plan_id: string | null;
  updated_at: Generated<Timestamp>;
  version: number | null;
}

export interface Projects {
  allowed_origins: Generated<string[]>;
  created_at: Generated<Timestamp>;
  demo: Generated<boolean>;
  description: Generated<string>;
  docs_url: string | null;
  features: Generated<string[]>;
  focus: string | null;
  id: Generated<string>;
  name: string;
  org_id: string;
  paused_at: Timestamp | null;
  paused_by: string | null;
  target_url: string;
  testing_confirmed_at: Timestamp | null;
  testing_confirmed_by: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RunEvents {
  at: Timestamp;
  id: Generated<Int8>;
  job_id: string;
  org_id: string;
  payload: Json;
  run_id: string;
  seq: number;
  type: string;
}

export interface Runs {
  agent_model: string;
  budget_usd: Numeric;
  cancel_reason: string | null;
  client_seen_at: Timestamp | null;
  completion_usd_per_mtok: Numeric | null;
  config_snapshot: Json;
  conversation: Generated<boolean>;
  cost_usd: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  created_by: string;
  execution: Generated<string>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  judge_model: string;
  max_steps: number;
  number: number;
  org_id: string;
  paid_by: Generated<string>;
  plan_id: string | null;
  plan_name: string;
  pr_plan: Json | null;
  project_id: string;
  prompt_usd_per_mtok: Numeric | null;
  provided_accounts: Generated<Json>;
  provider: Generated<string>;
  provider_base_url: string | null;
  pull_request: Json | null;
  replay_steps: number;
  sign_up_seed: string | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  target_override: Generated<boolean>;
  token_cap: Int8 | null;
  tokens_used: Generated<Int8>;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface SetupAttempts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
}

export interface SetupDrafts {
  created_at: Generated<Timestamp>;
  describe_failed_at: Timestamp | null;
  described_at: Timestamp | null;
  description: string | null;
  docs: string | null;
  docs_url: string | null;
  features: Json | null;
  id: Generated<string>;
  name: string | null;
  new_plan_name: string | null;
  org_id: string;
  origins: Generated<string[]>;
  page: string;
  plan_id: string | null;
  project_id: string | null;
  proposing_at: Timestamp | null;
  result_plan_id: string | null;
  result_project_id: string | null;
  sign_up: string | null;
  url: string;
}

export interface TargetAccounts {
  id: Generated<string>;
  org_id: string;
  password_hint: string;
  password_secret: string;
  plan_id: string;
  position: number;
  project_id: string;
  ref: string;
  username: string;
}

export interface TargetGates {
  id: Generated<string>;
  kind: string;
  name: string;
  org_id: string;
  plan_id: string;
  position: number;
  project_id: string;
  secret: string | null;
  secret_hint: string | null;
  value: string | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface WorkspaceBudgets {
  monthly_usd: Numeric;
  org_id: string;
  set_at: Generated<Timestamp>;
  set_by: string;
}

export interface WorkspaceMcpSettings {
  connections_allowed: Generated<boolean>;
  org_id: string;
  run_control_allowed: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface WorkspacePlans {
  extra_projects: Generated<number>;
  org_id: string;
  plan: string;
  set_at: Generated<Timestamp>;
  set_by: string;
}

export interface DB {
  account: Account;
  api_token_calls: ApiTokenCalls;
  api_tokens: ApiTokens;
  artifacts: Artifacts;
  credentials: Credentials;
  finding_dismissals: FindingDismissals;
  findings: Findings;
  first_runs_on_us: FirstRunsOnUs;
  goal_outcomes: GoalOutcomes;
  goals: Goals;
  invitation: Invitation;
  jobs: Jobs;
  llm_usage: LlmUsage;
  mcp_code_claims: McpCodeClaims;
  mcp_code_projects: McpCodeProjects;
  mcp_consent_contexts: McpConsentContexts;
  mcp_grants: McpGrants;
  mcp_rate_limits: McpRateLimits;
  member: Member;
  model_catalog: ModelCatalog;
  oauthAccessToken: OauthAccessToken;
  oauthClient: OauthClient;
  oauthClientAssertion: OauthClientAssertion;
  oauthClientResource: OauthClientResource;
  oauthConsent: OauthConsent;
  oauthRefreshToken: OauthRefreshToken;
  oauthResource: OauthResource;
  organization: Organization;
  personas: Personas;
  plans: Plans;
  projects: Projects;
  run_events: RunEvents;
  runs: Runs;
  session: Session;
  setup_attempts: SetupAttempts;
  setup_drafts: SetupDrafts;
  target_accounts: TargetAccounts;
  target_gates: TargetGates;
  user: User;
  verification: Verification;
  workspace_budgets: WorkspaceBudgets;
  workspace_mcp_settings: WorkspaceMcpSettings;
  workspace_plans: WorkspacePlans;
}
