/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Credentials {
  base_url: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  hint: string;
  id: Generated<string>;
  kind: string;
  org_id: string;
  secret: string;
}

export interface Findings {
  created_at: Generated<Timestamp>;
  goal: string;
  id: Generated<string>;
  job_id: string;
  key: string;
  kind: string;
  observed: string;
  org_id: string;
  persona_key: string;
  replay: Json | null;
  reproduction: Json;
  run_id: string;
  severity: string;
  title: string;
  updated_at: Generated<Timestamp>;
  verdict: string | null;
}

export interface GoalOutcomes {
  goal: string;
  note: Generated<string>;
  org_id: string;
  persona_key: string;
  run_id: string;
  status: string;
}

export interface Goals {
  id: Generated<string>;
  instruction: string;
  key: string;
  org_id: string;
  position: number;
  project_id: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Jobs {
  counted_cost: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  error: string | null;
  finding_key: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  lease_until: Timestamp | null;
  org_id: string;
  persona_key: string | null;
  position: number;
  run_id: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  stopped_by: string | null;
  token_hash: string | null;
  usage: Json | null;
}

export interface LlmUsage {
  cost_usd: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  input_tokens: number;
  job_id: string;
  model: string;
  org_id: string;
  output_tokens: number;
  run_id: string;
}

export interface Member {
  createdAt: Timestamp;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface ModelCatalog {
  completion_usd_per_mtok: Numeric;
  enabled: Generated<boolean>;
  id: string;
  label: string;
  note: string | null;
  position: number;
  prices_refreshed_at: Timestamp | null;
  prompt_usd_per_mtok: Numeric;
  recommended: Generated<boolean>;
}

export interface Organization {
  createdAt: Timestamp;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Personas {
  account_ref: string | null;
  brief: string;
  id: Generated<string>;
  key: string;
  name: string;
  org_id: string;
  position: number;
  project_id: string;
}

export interface Projects {
  allowed_origins: Generated<string[]>;
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  docs_url: string | null;
  focus: string | null;
  id: Generated<string>;
  name: string;
  org_id: string;
  target_url: string;
  updated_at: Generated<Timestamp>;
}

export interface RunEvents {
  at: Timestamp;
  id: Generated<Int8>;
  job_id: string;
  org_id: string;
  payload: Json;
  run_id: string;
  seq: number;
  type: string;
}

export interface Runs {
  agent_model: string;
  budget_usd: Numeric;
  completion_usd_per_mtok: Numeric | null;
  config_snapshot: Json;
  cost_usd: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  created_by: string;
  finished_at: Timestamp | null;
  id: Generated<string>;
  judge_model: string;
  max_steps: number;
  number: number;
  org_id: string;
  project_id: string;
  prompt_usd_per_mtok: Numeric | null;
  provider: Generated<string>;
  provider_base_url: string | null;
  replay_steps: number;
  started_at: Timestamp | null;
  status: Generated<string>;
  token_cap: Int8 | null;
  tokens_used: Generated<Int8>;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface SetupAttempts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
}

export interface TargetAccounts {
  id: Generated<string>;
  org_id: string;
  password_hint: string;
  password_secret: string;
  position: number;
  project_id: string;
  ref: string;
  username: string;
}

export interface TargetGates {
  id: Generated<string>;
  kind: string;
  name: string;
  org_id: string;
  position: number;
  project_id: string;
  secret: string | null;
  secret_hint: string | null;
  value: string | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  credentials: Credentials;
  findings: Findings;
  goal_outcomes: GoalOutcomes;
  goals: Goals;
  invitation: Invitation;
  jobs: Jobs;
  llm_usage: LlmUsage;
  member: Member;
  model_catalog: ModelCatalog;
  organization: Organization;
  personas: Personas;
  projects: Projects;
  run_events: RunEvents;
  runs: Runs;
  session: Session;
  setup_attempts: SetupAttempts;
  target_accounts: TargetAccounts;
  target_gates: TargetGates;
  user: User;
  verification: Verification;
}
