/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Goals {
  id: Generated<string>;
  instruction: string;
  key: string;
  org_id: string;
  position: number;
  project_id: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Member {
  createdAt: Timestamp;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Personas {
  account_ref: string | null;
  brief: string;
  id: Generated<string>;
  key: string;
  name: string;
  org_id: string;
  position: number;
  project_id: string;
}

export interface Projects {
  allowed_origins: Generated<string[]>;
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  docs_url: string | null;
  focus: string | null;
  id: Generated<string>;
  name: string;
  org_id: string;
  target_url: string;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface TargetAccounts {
  id: Generated<string>;
  org_id: string;
  password_hint: string;
  password_secret: string;
  position: number;
  project_id: string;
  ref: string;
  username: string;
}

export interface TargetGates {
  id: Generated<string>;
  kind: string;
  name: string;
  org_id: string;
  position: number;
  project_id: string;
  secret: string | null;
  secret_hint: string | null;
  value: string | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  goals: Goals;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  personas: Personas;
  projects: Projects;
  session: Session;
  target_accounts: TargetAccounts;
  target_gates: TargetGates;
  user: User;
  verification: Verification;
}
